version: "3.9"

services:
  orderdb:
    image: mysql:8.0
    container_name: orderdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - order_data:/var/lib/mysql

  order-service:
    build:
      context: .
    container_name: order-service
    ports:
      - "8086:8086"
    depends_on:
      - orderdb
    environment:
      DATABASE_URL: mysql+pymysql://user:password@orderdb:3306/orders

volumes:
  order_data:
