# Namespace (only needed once)
apiVersion: v1
kind: Namespace
metadata:
  name: iit-dev

---

# Deployment for Analytics Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: iit-dev
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: nuviii/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
              protocol: TCP
          env:
            - name: CLICKHOUSE_HOST
              value: clickhouse.clickhouse.svc.cluster.local
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: CLICKHOUSE_USER
              value: default
            - name: CLICKHOUSE_PASSWORD
              value: mypassword123
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always

---

# Service for Analytics Service
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: iit-dev
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087

---

# Ingress for Analytics Service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-ingress
  namespace: iit-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: analyticsservice.lugx.iit
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 8087
